### ISSUE TITLE
track not recorded (except the first one after opening the software). see example in file attached

### ISSUE THREAD

**Issue by hannebel** [deepakkrishnamurthy/gravitymachine-research#11]
[002_2021-05-04 15-20-18.zip](https://github.com/deepakkrishnamurthy/gravitymachine-research/files/6424748/002_2021-05-04.15-20-18.zip)

**Comment by deepakkrishnamurthy** [comment]
@deepakkrishnamurthy : I will look into this (also testing my notification settings).

**Comment by deepakkrishnamurthy** [comment]
Recreated issue on personal Macbook Pro (with no hardware connected).

**Comment by deepakkrishnamurthy** [comment]
Issue fixed. Bug was due to the thread used for saving data to become stopped when acquisition was stopped. In subsequent acquisitions the thread was not able to start again, hence causing the issue. Also improved the code by not sending data to the queue when acquisition is not enabled. 

![image](https://user-images.githubusercontent.com/26558087/120564452-cff45c00-c3bf-11eb-88cf-3583537371f4.png)

screen-shot shows file with data-saved correctly after multiple acquisition button presses.

**Comment by deepakkrishnamurthy** [comment]
@hannebel : Kindly pull latest commit on master and confirm this works on the live machines.
